import {database} from '@/db/storage';
import {articleView,type ArticleRow} from '@/lib/server/catalogue';
import {articleSchema} from '@/lib/catalogue';
import {identity,json,validOrigin,payload} from '@/lib/server/access';
export async function POST(r:Request){return write(r,false)}
export async function PUT(r:Request){return write(r,true)}
async function write(r:Request,edit:boolean){const user=identity(r);if(!user)return json({error:'ورود لازم است. / Sign in first.'},401);if(!validOrigin(r))return json({error:'Invalid origin'},403);try{const body=await payload(r);const parsed=articleSchema.safeParse(body.article);if(!parsed.success)return json({error:parsed.error.issues[0].message},400);const db=database(),profile=await db.prepare('SELECT id,published FROM teacher_public_profiles WHERE owner_id=?').bind(user.id).first<{id:string,published:number}>();if(!profile)return json({error:'ابتدا پرتفولیوی خود را ثبت کنید. / Create your portfolio first.'},400);if(parsed.data.status==='published'&&!profile.published)return json({error:'ابتدا پرتفولیو را منتشر کنید؛ سپس مقاله را منتشر کنید. / Publish your portfolio before publishing articles.'},400);const stored={...parsed.data,readingMinutes:Math.max(1,Math.ceil(parsed.data.content.split(/\s+/).length/180))};const now=new Date().toISOString();if(edit){if(typeof body.id!=='string'||!Number.isSafeInteger(body.version))return json({error:'Invalid request'},400);const changed=await db.prepare('UPDATE teacher_articles SET data=?,status=?,version=version+1,updated_at=? WHERE id=? AND owner_id=? AND version=?').bind(JSON.stringify(stored),parsed.data.status,now,body.id,user.id,body.version).run();if(!changed.meta.changes)return json({error:'مقاله تغییر کرده یا در دسترس شما نیست. / Article changed or unavailable.'},409);return json({id:body.id,version:body.version+1})}const id=crypto.randomUUID();await db.prepare('INSERT INTO teacher_articles (id,owner_id,teacher_id,data,status,version,created_at,updated_at) VALUES (?,?,?,?,?,1,?,?)').bind(id,user.id,profile.id,JSON.stringify(stored),parsed.data.status,now,now).run();return json({id,version:1},201)}catch(e){console.error('Article save failed',e);return json({error:'ذخیره مقاله انجام نشد. / Article save failed.'},503)}}
export async function DELETE(r:Request){const user=identity(r);if(!user)return json({error:'Sign in first'},401);if(!validOrigin(r))return json({error:'Invalid origin'},403);try{const body=await payload(r);if(typeof body.id!=='string'||!Number.isSafeInteger(body.version))return json({error:'Invalid request'},400);const result=await database().prepare('DELETE FROM teacher_articles WHERE id=? AND owner_id=? AND version=?').bind(body.id,user.id,body.version).run();if(!result.meta.changes)return json({error:'مقاله تغییر کرده یا در دسترس شما نیست. / Article changed or unavailable.'},409);return json({deleted:true})}catch{return json({error:'حذف انجام نشد. / Delete failed.'},503)}}

export async function GET(r:Request){const user=identity(r);if(!user)return json({error:'Sign in first'},401);try{const id=new URL(r.url).searchParams.get('id');if(!id)return json({error:'Article ID required'},400);const row=await database().prepare('SELECT * FROM teacher_articles WHERE id=? AND owner_id=?').bind(id,user.id).first<ArticleRow>();return row?json({article:articleView(row)}):json({error:'مقاله پیدا نشد. / Article not found.'},404)}catch{return json({error:'دریافت مقاله انجام نشد. / Could not load article.'},503)}}
