import {database} from '@/db/storage';
import {type Teacher,type Article,type Catalogue,type PublicProfileInput,initialPublicProfile} from '@/lib/catalogue';
type ProfileRow={id:string,owner_id:string,data:string,published:number,version:number,updated_at:string};
type ArticleRow={id:string,owner_id:string,teacher_id:string,data:string,status:string,version:number,created_at:string,updated_at:string};
export function profileView(row:ProfileRow):Teacher{return {...JSON.parse(row.data),id:row.id,published:!!row.published,version:row.version,updatedAt:row.updated_at,photo:'/api/public-photo/'+row.id+'?v='+row.version}}
export function articleView(row:ArticleRow):Article{return {content:'',...JSON.parse(row.data),id:row.id,teacherId:row.teacher_id,status:row.status,version:row.version,createdAt:row.created_at,updatedAt:row.updated_at}}
export async function publicCatalogue(isAdmin=false):Promise<Catalogue>{const db=database();const [profiles,posts]=await Promise.all([db.prepare('SELECT * FROM teacher_public_profiles WHERE published=1 ORDER BY updated_at DESC LIMIT 500').all<ProfileRow>(),db.prepare("SELECT a.id,a.owner_id,a.teacher_id,json_remove(a.data,'$.content') AS data,a.status,a.version,a.created_at,a.updated_at FROM teacher_articles a INNER JOIN teacher_public_profiles p ON p.id=a.teacher_id WHERE a.status='published' AND p.published=1 ORDER BY a.created_at DESC LIMIT 500").all<ArticleRow>()]);return {teachers:profiles.results.map(profileView),articles:posts.results.map(articleView),isAdmin}}
export async function ownStudio(ownerId:string,defaultName:string){const db=database();let profile=await db.prepare('SELECT * FROM teacher_public_profiles WHERE owner_id=?').bind(ownerId).first<ProfileRow>();if(!profile){const workspace=await db.prepare('SELECT data FROM teacher_workspaces WHERE owner_id=?').bind(ownerId).first<{data:string}>();const w=workspace?JSON.parse(workspace.data):null;const p=initialPublicProfile(w&&!w.demo?w.profile.name:defaultName);if(w&&!w.demo){p.bio=w.profile.bio||'';p.headline=w.profile.specialization||'';p.currency=w.profile.currency||'TOMAN'}await db.prepare('INSERT OR IGNORE INTO teacher_public_profiles (id,owner_id,data,published,version,updated_at) VALUES (?,?,?,0,1,?)').bind(crypto.randomUUID(),ownerId,JSON.stringify(p),new Date().toISOString()).run();profile=await db.prepare('SELECT * FROM teacher_public_profiles WHERE owner_id=?').bind(ownerId).first<ProfileRow>()}const posts=await db.prepare("SELECT id,owner_id,teacher_id,json_remove(data,'$.content') AS data,status,version,created_at,updated_at FROM teacher_articles WHERE owner_id=? ORDER BY updated_at DESC LIMIT 500").bind(ownerId).all<ArticleRow>();return {profile:profileView(profile!),articles:posts.results.map(articleView)}}
export type {ProfileRow,ArticleRow};
