import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile,readdir} from 'node:fs/promises';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';

test('portfolios, articles, enquiries and admin access preserve ownership and quoted currency',async()=>{
 const files=(await readdir('dist/server',{recursive:true})).filter(p=>p.endsWith('.js')&&p!=='index.js');
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'app',modules:[{type:'ESModule',path:'dist/server/index.js'},...files.map(p=>({type:'ESModule',path:'dist/server/'+p}))],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],serviceBindings:{ASSETS:()=>new Response('Not found',{status:404})}}]}));
 try{
  const db=await mf.getD1Database('DB');
  for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.exec(sql.replace(/\n/g,' '));
  const req=(path,user,method='GET',body)=>mf.dispatchFetch('http://workspace.test'+path,{method,headers:{...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user==='admin'?'lahzetv@gmail.com':user+'@example.com'}:{}),...(body?{'Content-Type':'application/json',Origin:'http://workspace.test'}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const ok=async(response,status=200)=>{assert.equal(response.status,status,await response.clone().text());return response.json()};
  for(const path of ['/','/teachers','/blog','/contact','/teachers/sample-sara','/blog/sample-small-steps'])assert.equal((await req(path)).status,200,path);
  assert.equal((await req('/api/studio')).status,401);
  const workspace=await ok(await req('/api/workspace','teacher-a'));
  workspace.data.demo=false;workspace.data.profile.name='Private Account Name';workspace.data.profile.email='private@example.com';
  await ok(await req('/api/workspace','teacher-a','PUT',workspace));
  const studio=await ok(await req('/api/studio','teacher-a'));
  assert.equal(studio.profile.published,false);
  assert.equal((await ok(await req('/api/catalogue'))).teachers.length,0);
  const profile={...studio.profile,name:'معلم آزمایشی',headline:'تمرین مکالمه انگلیسی',bio:'معرفی واقعی برای بررسی مسیر انتشار پرتفولیو و ارائه کلاس‌های زبان با تمرین و بازخورد آموزشی.',published:true,currency:'USD',rate:24.99,languages:['en'],formats:['online']};
  await ok(await req('/api/studio/profile','teacher-a','PUT',{profile,version:1}));
  let listing=await ok(await req('/api/catalogue'));
  assert.equal(listing.teachers[0].rate,24.99);assert.equal(listing.teachers[0].currency,'USD');
  assert(!JSON.stringify(listing).includes('private@example.com'));assert(!JSON.stringify(listing).includes('owner_id'));
  assert.equal((await req('/api/studio/profile','teacher-a','PUT',{profile,version:1})).status,409);
  const article={title:'Learning through conversation',excerpt:'A teacher-authored article.',content:'A private draft paragraph with useful learning advice. '.repeat(8),category:'learning',status:'draft'};
  const created=await ok(await req('/api/studio/posts','teacher-a','POST',{article}),201);
  assert.equal((await ok(await req('/api/catalogue'))).articles.length,0);
  assert.equal((await ok(await req('/api/studio/posts?id='+created.id,'teacher-a'))).article.content,article.content.trim());
  assert.equal((await req('/api/studio/posts?id='+created.id,'teacher-b')).status,404);
  await ok(await req('/api/studio','teacher-b'));
  assert.equal((await req('/api/studio/posts','teacher-b','PUT',{id:created.id,version:1,article})).status,409);
  assert.equal((await req('/api/studio/posts','teacher-b','DELETE',{id:created.id,version:1})).status,409);
  await ok(await req('/api/studio/posts','teacher-a','PUT',{id:created.id,version:1,article:{...article,status:'published'}}));
  listing=await ok(await req('/api/catalogue'));
  assert.equal((await req('/teachers/'+profile.id)).status,200);assert.equal((await req('/blog/'+created.id)).status,200);
  assert.equal(listing.articles.length,1);assert.equal(listing.articles[0].content,'');assert(listing.articles[0].readingMinutes>=1);
  const inquiry={id:crypto.randomUUID(),kind:'class',teacherId:profile.id,teacherVersion:2,name:'Learner One',email:'learner@example.com',phone:'09121234567',language:'en',format:'online',message:'I would like to arrange a class.',rate:1,currency:'TOMAN'};
  await ok(await req('/api/requests',undefined,'POST',inquiry),201);
  await ok(await req('/api/requests',undefined,'POST',inquiry));
  assert.equal((await req('/api/requests',undefined,'POST',{...inquiry,id:crypto.randomUUID(),language:'de'})).status,400);
  assert.equal((await req('/api/requests',undefined,'POST',{...inquiry,id:crypto.randomUUID(),format:'in-person'})).status,400);
  assert.equal((await req('/api/requests',undefined,'POST',{...inquiry,id:crypto.randomUUID(),teacherVersion:1})).status,409);
  assert.equal((await req('/api/admin/requests')).status,403);
  assert.equal((await req('/api/admin/requests','teacher-a')).status,403);
  let inbox=await ok(await req('/api/admin/requests','admin'));
  assert.equal(inbox.requests.length,1);assert.equal(inbox.requests[0].rate,24.99);assert.equal(inbox.requests[0].currency,'USD');
  await ok(await req('/api/admin/requests','admin','PUT',{id:inquiry.id,version:1,status:'reviewing',adminNote:'Private follow-up note'}));
  assert.equal((await req('/api/admin/requests','admin','PUT',{id:inquiry.id,version:1,status:'closed',adminNote:''})).status,409);
  await ok(await req('/api/studio/profile','teacher-a','PUT',{profile:{...profile,currency:'TOMAN',rate:450000},version:2}));
  inbox=await ok(await req('/api/admin/requests','admin'));
  assert.equal(inbox.requests[0].currency,'USD');assert.equal(inbox.requests[0].rate,24.99);assert.equal(inbox.requests[0].status,'reviewing');
  assert.equal((await req('/api/requests',undefined,'POST',{...inquiry,id:crypto.randomUUID()})).status,409);
  const contact={id:crypto.randomUUID(),kind:'contact',name:'Learner One',email:'learner@example.com',message:'Please help me choose a teacher.'};
  for(let i=0;i<4;i++)await ok(await req('/api/requests',undefined,'POST',{...contact,id:crypto.randomUUID()}),201);
  assert.equal((await req('/api/requests',undefined,'POST',{...contact,id:crypto.randomUUID()})).status,429);
  assert.equal((await mf.dispatchFetch('http://workspace.test/api/requests',{method:'POST',headers:{Origin:'http://untrusted.test','Content-Type':'application/json'},body:JSON.stringify(contact)})).status,403);
  await ok(await req('/api/studio/profile','teacher-a','PUT',{profile:{...profile,published:false},version:3}));
  listing=await ok(await req('/api/catalogue'));assert.equal(listing.teachers.length,0);assert.equal(listing.articles.length,0);
  assert.equal((await req('/api/public-photo/'+profile.id)).status,404);
  assert.equal((await req('/api/requests',undefined,'POST',{...inquiry,id:crypto.randomUUID(),teacherVersion:4})).status,400);
  const own=await ok(await req('/api/studio','teacher-a'));assert.equal(own.articles.length,1);
  await ok(await req('/api/studio/posts','teacher-a','DELETE',{id:created.id,version:2}));
  assert.equal((await ok(await req('/api/studio','teacher-a'))).articles.length,0);
  // An old portfolio and its articles remain reachable outside the discovery cap.
  const inserts=Array.from({length:501},(_,i)=>db.prepare('INSERT INTO teacher_public_profiles (id,owner_id,data,published,version,updated_at) VALUES (?,?,?,1,1,?)').bind('cap-'+i,'cap-owner-'+i,JSON.stringify({...profile,name:'Teacher '+i}),i===0?'2020-01-01T00:00:00Z':'2030-01-01T00:00:00Z'));
  await db.batch(inserts);
  await db.prepare("INSERT INTO teacher_articles (id,owner_id,teacher_id,data,status,version,created_at,updated_at) VALUES (?,?,?, ?,'published',1,?,?)").bind('cap-post','cap-owner-0','cap-0',JSON.stringify({...article,title:'Older teacher article',status:'published'}),'2020-01-01T00:00:00Z','2020-01-01T00:00:00Z').run();
  assert(!(await ok(await req('/api/catalogue'))).teachers.some(t=>t.id==='cap-0'));
  const older=await req('/teachers/cap-0');assert.equal(older.status,200);assert((await older.text()).includes('Older teacher article'));
  const olderPost=await req('/blog/cap-post');assert.equal(olderPost.status,200);assert((await olderPost.text()).includes('Teacher 0'));

 }finally{await mf.dispose()}
});
