import {z} from 'zod';
import {validMoney,type Currency} from './model';
export const languageCodes=['en','fr','de','es','tr','ar','fa','it'] as const;
export const languages={en:['انگلیسی','English'],fr:['فرانسوی','French'],de:['آلمانی','German'],es:['اسپانیایی','Spanish'],tr:['ترکی','Turkish'],ar:['عربی','Arabic'],fa:['فارسی','Persian'],it:['ایتالیایی','Italian']} as const;
export const articleCategories={learning:['یادگیری زبان','Learning'],conversation:['مکالمه','Conversation'],exams:['آزمون‌ها','Exams'],culture:['فرهنگ و زبان','Culture']} as const;
export const publicProfileSchema=z.object({name:z.string().trim().min(2).max(100),headline:z.string().trim().max(150),bio:z.string().trim().max(5000),languages:z.array(z.enum(languageCodes)).min(1).max(8),formats:z.array(z.enum(['online','in-person'])).min(1).max(2),city:z.string().trim().max(100),experience:z.number().int().min(0).max(70),education:z.string().trim().max(2000),certificates:z.string().trim().max(2000),specialties:z.string().trim().max(600),rate:z.number().min(0).max(100000000),currency:z.enum(['TOMAN','USD']),duration:z.number().int().min(15).max(300),published:z.boolean()}).superRefine((p,c)=>{if(!validMoney(p.rate,p.currency))c.addIssue({code:'custom',path:['rate'],message:'مبلغ معتبر وارد کنید؛ دلار حداکثر دو رقم اعشار دارد. / Invalid amount.'});if(p.published&&(!p.headline||p.bio.length<40))c.addIssue({code:'custom',message:'برای نمایش پرتفولیو، عنوان و معرفی حداقل ۴۰ کاراکتری وارد کنید. / Add a headline and a bio of at least 40 characters.'});if(p.formats.includes('in-person')&&!p.city)c.addIssue({code:'custom',path:['city'],message:'برای کلاس حضوری شهر را مشخص کنید. / Enter a city for in-person classes.'})});
export type PublicProfileInput=z.infer<typeof publicProfileSchema>;
export type Teacher=PublicProfileInput&{id:string,photo:string,updatedAt:string,version:number,sample?:boolean};
export const articleSchema=z.object({title:z.string().trim().min(3).max(180),excerpt:z.string().trim().max(350),content:z.string().trim().min(30).max(50000),category:z.enum(['learning','conversation','exams','culture']),status:z.enum(['draft','published'])}).superRefine((p,c)=>{if(p.status==='published'&&p.content.length<150)c.addIssue({code:'custom',message:'برای انتشار، متن مقاله باید حداقل ۱۵۰ کاراکتر باشد. / Add at least 150 characters to publish.'})});
export type ArticleInput=z.infer<typeof articleSchema>;
export type Article=ArticleInput&{id:string,teacherId:string,createdAt:string,updatedAt:string,version:number,readingMinutes?:number,sample?:boolean};
export const inquirySchema=z.object({id:z.string().uuid(),kind:z.enum(['class','contact']),teacherId:z.string().max(100).default(''),teacherVersion:z.number().int().positive().optional(),name:z.string().trim().min(2).max(100),email:z.string().trim().email().max(200),phone:z.string().trim().max(30).default(''),language:z.string().max(10).default(''),format:z.enum(['online','in-person','']).default(''),message:z.string().trim().min(5).max(4000),website:z.string().max(100).default('')});
export type InquiryInput=z.infer<typeof inquirySchema>;
export type Inquiry=Omit<InquiryInput,'website'>&{teacherName:string,rate:number|null,currency:Currency|null,duration:number|null,status:'new'|'reviewing'|'closed',adminNote:string,createdAt:string,updatedAt:string,version:number};
export type Catalogue={teachers:Teacher[],articles:Article[],isAdmin:boolean,error?:string};
export function initialPublicProfile(name=''):PublicProfileInput{return {name,headline:'',bio:'',languages:['en'],formats:['online'],city:'',experience:0,education:'',certificates:'',specialties:'',rate:250000,currency:'TOMAN',duration:60,published:false}}
export function matchesTeacher(t:Teacher,filters:{query?:string,language?:string,format?:string,currency?:string,maxPrice?:string,city?:string}){const q=(filters.query||'').trim().toLowerCase();return (!q||(t.name+' '+t.headline+' '+t.specialties).toLowerCase().includes(q))&&(!filters.language||filters.language==='all'||t.languages.includes(filters.language as typeof languageCodes[number]))&&(!filters.format||filters.format==='all'||t.formats.includes(filters.format as 'online'|'in-person'))&&(!filters.currency||filters.currency==='all'||t.currency===filters.currency)&&(!filters.maxPrice||filters.currency==='all'||!filters.currency||t.rate<=Number(filters.maxPrice))&&(!filters.city||t.city.toLowerCase().includes(filters.city.toLowerCase()))}
export const sampleTeachers:Teacher[]=[
 {...initialPublicProfile('سارا مهر'),id:'sample-sara',headline:'مکالمه‌ای که از زندگی شروع می‌شود',bio:'این یک پرتفولیوی نمونه برای نمایش امکانات سایت است. در معرفی واقعی می‌توانید روش تدریس، هدف‌های آموزشی و تجربه خود را توضیح دهید. کلاس‌ها می‌توانند با توجه به سطح و نیاز هر زبان‌آموز برنامه‌ریزی شوند.',languages:['en'],formats:['online','in-person'],city:'تهران',experience:6,education:'محل درج تحصیلات معلم',certificates:'محل درج گواهی‌های واقعی',specialties:'مکالمه روزمره، انگلیسی سفر',rate:450000,currency:'TOMAN',duration:60,published:true,photo:'',updatedAt:'2026-09-05T08:00:00Z',version:1,sample:true},
 {...initialPublicProfile('آرمان راد'),id:'sample-arman',headline:'قدم‌به‌قدم تا گفت‌وگوی آلمانی',bio:'این پروفایل نمونه است و معلم واقعی معرفی نمی‌کند. معلم می‌تواند در این بخش درباره ساختار کلاس، تمرین‌های پیشنهادی و شیوه بازخورد خود بنویسد. اطلاعات واقعی پس از ثبت و انتشار جایگزین می‌شوند.',languages:['de','en'],formats:['online'],city:'',experience:4,education:'محل درج تحصیلات معلم',certificates:'محل درج گواهی‌های واقعی',specialties:'آلمانی مقدماتی، آمادگی مکالمه',rate:22.5,currency:'USD',duration:60,published:true,photo:'',updatedAt:'2026-09-05T08:00:00Z',version:1,sample:true},
 {...initialPublicProfile('لیلا نوید'),id:'sample-leila',headline:'فرانسه را از واژه‌ها فراتر ببرید',bio:'این یک معرفی نمونه برای پیش‌نمایش پرتفولیوی معلم است. در صفحه واقعی، زبان‌آموز می‌تواند زبان‌ها، هزینه هر جلسه، شهر کلاس حضوری و نوشته‌های آموزشی معلم را ببیند و درخواستش را برای مدیریت ارسال کند.',languages:['fr'],formats:['online','in-person'],city:'اصفهان',experience:5,education:'محل درج تحصیلات معلم',certificates:'محل درج گواهی‌های واقعی',specialties:'فرانسوی روزمره، تلفظ',rate:390000,currency:'TOMAN',duration:45,published:true,photo:'',updatedAt:'2026-09-05T08:00:00Z',version:1,sample:true}
];
export const sampleArticles:Article[]=[
 {id:'sample-small-steps',teacherId:'sample-sara',title:'هر روز کمی زبان؛ چطور یک عادت ماندگار بسازیم؟',excerpt:'قرار نیست هر روز یک فصل کتاب بخوانید. گاهی یک گفت‌وگوی کوتاه، شروع بهتری است.',content:'برای ساختن عادت یادگیری، فعالیتی را انتخاب کنید که در یک روز شلوغ هم بتوانید انجامش دهید. مثلاً چند جمله درباره روزتان بنویسید یا یک فایل صوتی کوتاه را گوش کنید.\n\n## یک موقعیت واقعی انتخاب کنید\nبه چیزی فکر کنید که دوست دارید به زبان جدید بگویید: سفارش غذا، معرفی خودتان یا توضیح یک علاقه شخصی. چند عبارت کاربردی برای همان موقعیت جمع کنید و با صدای بلند تمرین کنید.\n\n## تمرین کوچک را قابل تکرار کنید\nتمرین را به یکی از کارهای روزمره وصل کنید. بعد از صبحانه یا پیش از رفتن به محل کار، چند دقیقه برای مرور عبارت‌های دیروز کنار بگذارید. زمان کوتاه و مشخص، برنامه را قابل اجرا می‌کند.\n\n## از معلم بازخورد بگیرید\nنمونه‌ای از تمرینتان را به کلاس ببرید. معلم می‌تواند به شما کمک کند خطاهای تکراری را پیدا کنید و برای مرحله بعد هدفی متناسب با سطح خودتان بگذارید.',category:'learning',status:'published',createdAt:'2026-09-05T08:00:00Z',updatedAt:'2026-09-05T08:00:00Z',version:1,sample:true},
 {id:'sample-speaking',teacherId:'sample-arman',title:'قبل از اولین کلاس مکالمه، این سه سؤال را از خودتان بپرسید',excerpt:'هدفتان از یادگیری، موقعیت‌های موردنیاز و زمان تمرین را روشن کنید.',content:'شروع یک کلاس جدید فرصت خوبی برای مشخص کردن انتظارات است. لازم نیست همه پاسخ‌ها را از قبل بدانید؛ همین که درباره نیازهایتان فکر کنید، گفت‌وگوی اول با معلم مفیدتر می‌شود.\n\n## برای چه موقعیتی زبان می‌خواهید؟\nکار، سفر، تحصیل یا گفت‌وگو با دوستان؟ یک یا دو موقعیت را مشخص کنید تا بتوانید از معلم درباره محتوای مناسب آن‌ها بپرسید.\n\n## کجا بیشتر مکث می‌کنید؟\nآیا پیدا کردن واژه‌ها سخت است یا شنیدن پاسخ طرف مقابل؟ نمونه‌ای واقعی از تجربه خودتان آماده کنید و با معلم در میان بگذارید.\n\n## چه زمانی برای تمرین دارید؟\nیک برنامه واقع‌بینانه با زمان‌های کوتاه بهتر از برنامه‌ای است که نتوانید ادامه‌اش دهید. درباره تمرین بین جلسات و نوع بازخورد با معلم توافق کنید.',category:'conversation',status:'published',createdAt:'2026-09-04T08:00:00Z',updatedAt:'2026-09-04T08:00:00Z',version:1,sample:true},
 {id:'sample-online-class',teacherId:'sample-leila',title:'کلاس آنلاین یا حضوری؛ کدام با زندگی شما سازگارتر است؟',excerpt:'به مسیر رفت‌وآمد، فضای تمرین و شیوه ارتباطی موردعلاقه‌تان نگاه کنید.',content:'انتخاب کلاس آنلاین یا حضوری به برنامه روزانه و ترجیح یادگیری شما بستگی دارد. پیش از انتخاب، به این فکر کنید که در چه شرایطی راحت‌تر تمرکز می‌کنید.\n\n## فضای یادگیری را بررسی کنید\nبرای کلاس آنلاین به فضایی آرام و ارتباط اینترنتی مناسب نیاز دارید. برای کلاس حضوری، زمان و هزینه رفت‌وآمد را در برنامه خود حساب کنید.\n\n## درباره شیوه کلاس بپرسید\nاز معلم بپرسید تمرین‌ها چطور انجام می‌شوند، بازخورد به چه صورت است و چه منابعی برای بین جلسات پیشنهاد می‌کند. شیوه تدریس به اندازه قالب کلاس اهمیت دارد.\n\n## هزینه هر جلسه را در کنار مدت آن ببینید\nمدت کلاس‌ها ممکن است متفاوت باشد. برای مقایسه، هم مدت جلسه و هم واحد پول را بررسی کنید و جزئیات نهایی را با مدیریت هماهنگ کنید.',category:'learning',status:'published',createdAt:'2026-09-03T08:00:00Z',updatedAt:'2026-09-03T08:00:00Z',version:1,sample:true}
];
